[package]
name = "transcribe-words"
version = "0.2.0"
edition = "2021"

[lib]
name = "transcribe_words"
crate-type = ["cdylib"]

[dependencies]
whisper-core = { path = "../core" }
ffrwd-node = { git = "https://github.com/imbcmdth/ffrwd-node", tag = "v0.2.0" }
wit-bindgen = "0.57.1"
serde_json = "1"
